# Generated by Django 5.2.17 on 2026-09-02 16:57

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=80, unique=True)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'categoría',
                'verbose_name_plural': 'categorías',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(1)])),
                ('capacidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'mesa',
                'verbose_name_plural': 'mesas',
                'ordering': ['numero'],
            },
        ),
        migrations.CreateModel(
            name='Mesero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'mesero',
                'verbose_name_plural': 'meseros',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Comanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('fecha_apertura', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('fecha_cierre', models.DateTimeField(blank=True, editable=False, null=True)),
                ('mesa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='comandas.mesa')),
                ('mesero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='comandas', to='comandas.mesero')),
            ],
            options={
                'verbose_name': 'comanda',
                'verbose_name_plural': 'comandas',
                'ordering': ['-fecha_apertura'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='comandas.categoria')),
            ],
            options={
                'verbose_name': 'producto',
                'verbose_name_plural': 'productos',
                'ordering': ['categoria__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='DetalleComanda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('precio_unitario', models.DecimalField(decimal_places=2, editable=False, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('comanda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='comandas.comanda')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='detalles_comanda', to='comandas.producto')),
            ],
            options={
                'verbose_name': 'detalle de comanda',
                'verbose_name_plural': 'detalles de comanda',
                'ordering': ['id'],
            },
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.UniqueConstraint(condition=models.Q(('estado', 'ABIERTA')), fields=('mesa',), name='una_comanda_abierta_por_mesa'),
        ),
        migrations.AddConstraint(
            model_name='comanda',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('estado', 'ABIERTA'), ('fecha_cierre__isnull', True)), models.Q(('estado', 'CERRADA'), ('fecha_cierre__gte', models.F('fecha_apertura')), ('fecha_cierre__isnull', False)), _connector='OR'), name='comanda_estado_fechas_consistentes'),
        ),
        migrations.AddConstraint(
            model_name='producto',
            constraint=models.UniqueConstraint(fields=('categoria', 'nombre'), name='producto_unico_por_categoria'),
        ),
        migrations.AddConstraint(
            model_name='detallecomanda',
            constraint=models.UniqueConstraint(fields=('comanda', 'producto'), name='producto_unico_por_comanda'),
        ),
        migrations.AddConstraint(
            model_name='detallecomanda',
            constraint=models.CheckConstraint(condition=models.Q(('cantidad__gt', 0)), name='detalle_cantidad_positiva'),
        ),
        migrations.AddConstraint(
            model_name='detallecomanda',
            constraint=models.CheckConstraint(condition=models.Q(('precio_unitario__gte', 0)), name='detalle_precio_no_negativo'),
        ),
    ]
